---
sudo: required

env:
  - distro: centos7
    playbook: test.yml
  - distro: centos6
    playbook: test.yml
  - distro: debian8
    playbook: test.yml
  - distro: debian9
    playbook: test.yml
  - distro: ubuntu1604
    playbook: test.yml
  - distro: ubuntu1404
    playbook: test.yml

services:
  - docker

script:

# Download test shim.
 - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
 - chmod +x ${PWD}/tests/test.sh
#Running the test
 - ${PWD}/tests/test.sh
